In [4]:
from sklearn import tree
import pandas as pd

In [5]:
data = pd.read_csv("C:\Users\wacalvo\Desktop\Personas.csv", header=0)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-5-eb9ec813f727>, line 1)

In [6]:
data = pd.read_csv('C:\Users\wacalvo\Desktop\Personas.csv', header=0)

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-6-cb8842504ab8>, line 1)

In [7]:
data = pd.read_csv(r'C:\Users\wacalvo\Desktop\Personas.csv', header=0)

In [8]:
data

   Sexo  Estatura  Peso Altura
0     h        35    75    1,7
1     m        57    88   1,59
2     h        40    81   1,66
3     h        46    73   1,66
4     m        67    97   1,68
5     m        68    99   1,58
6     m        65    85   1,56
7     h        60    70   1,65
8     h        56    94   1,72
9     m        66    68   1,51
10    h        54    87   1,73
11    h        52    87   1,82
12    m        65    82   1,58
13    m        55    79   1,55
14    m        67    91   1,61
15    h        45    96   1,78
16    h        44    92    1,8
17    m        38    65    1,6
18    h        34    75    1,7
19    h        39    84   1,67
20    m        44    81   1,66
21    m        44    73   1,66
22    m        43    97   1,68
23    h        48    95   1,58
24    h        50    89   1,56
25    m        44    71   1,65
26    h        57    94   1,72
27    m        59    68   1,51
28    h        44    91   1,73
29    h        36    83   1,82
..  ...       ...   ...    ...
70    m        52    79   1,66
71    h        65    87   1,83
72    h        55    96    1,8
73    m        67    96   1,58
74    m        45    65   1,56
75    m        44    94   1,65
76    h        38    90   1,72
77    h        34    81   1,51
78    m        39    87   1,65
79    h        44    93   1,82
80    h        38    77   1,58
81    m        71    71   1,55
82    m        78    67   1,61
83    m        55    80   1,57
84    h        44    70   1,56
85    h        43    94   1,72
86    m        48    64   1,51
87    h        50    87   1,73
88    h        39    83   1,82
89    m        44    86   1,58
90    m        38    75   1,55
91    m        34    71   1,61
92    h        39    85   1,78
93    h        55    96    1,8
94    m        72    65    1,6
95    h        43    90    1,7
96    m        48    93   1,73
97    h        50    79    1,7
98    h        45    88    1,6
99    m        58    81   1,66

[100 rows x 4 columns]

In [9]:
datos["Sexo"]

NameError: name 'datos' is not defined

In [10]:
data["Sexo"]

0     h
1     m
2     h
3     h
4     m
5     m
6     m
7     h
8     h
9     m
10    h
11    h
12    m
13    m
14    m
15    h
16    h
17    m
18    h
19    h
20    m
21    m
22    m
23    h
24    h
25    m
26    h
27    m
28    h
29    h
     ..
70    m
71    h
72    h
73    m
74    m
75    m
76    h
77    h
78    m
79    h
80    h
81    m
82    m
83    m
84    h
85    h
86    m
87    h
88    h
89    m
90    m
91    m
92    h
93    h
94    m
95    h
96    m
97    h
98    h
99    m
Name: Sexo, Length: 100, dtype: object

In [11]:
clear

In [12]:

for contador in data: 
    print("hola ")

hola
hola
hola
hola

In [13]:
for contador in data: 
    print("hola ")

hola
hola
hola
hola

In [14]:
data

   Sexo  Estatura  Peso Altura
0     h        35    75    1,7
1     m        57    88   1,59
2     h        40    81   1,66
3     h        46    73   1,66
4     m        67    97   1,68
5     m        68    99   1,58
6     m        65    85   1,56
7     h        60    70   1,65
8     h        56    94   1,72
9     m        66    68   1,51
10    h        54    87   1,73
11    h        52    87   1,82
12    m        65    82   1,58
13    m        55    79   1,55
14    m        67    91   1,61
15    h        45    96   1,78
16    h        44    92    1,8
17    m        38    65    1,6
18    h        34    75    1,7
19    h        39    84   1,67
20    m        44    81   1,66
21    m        44    73   1,66
22    m        43    97   1,68
23    h        48    95   1,58
24    h        50    89   1,56
25    m        44    71   1,65
26    h        57    94   1,72
27    m        59    68   1,51
28    h        44    91   1,73
29    h        36    83   1,82
..  ...       ...   ...    ...
70    m        52    79   1,66
71    h        65    87   1,83
72    h        55    96    1,8
73    m        67    96   1,58
74    m        45    65   1,56
75    m        44    94   1,65
76    h        38    90   1,72
77    h        34    81   1,51
78    m        39    87   1,65
79    h        44    93   1,82
80    h        38    77   1,58
81    m        71    71   1,55
82    m        78    67   1,61
83    m        55    80   1,57
84    h        44    70   1,56
85    h        43    94   1,72
86    m        48    64   1,51
87    h        50    87   1,73
88    h        39    83   1,82
89    m        44    86   1,58
90    m        38    75   1,55
91    m        34    71   1,61
92    h        39    85   1,78
93    h        55    96    1,8
94    m        72    65    1,6
95    h        43    90    1,7
96    m        48    93   1,73
97    h        50    79    1,7
98    h        45    88    1,6
99    m        58    81   1,66

[100 rows x 4 columns]

In [15]:
for contador in data: 
    print(contador)

Sexo
Estatura
Peso
Altura

In [16]:
data

   Sexo  Estatura  Peso Altura
0     h        35    75    1,7
1     m        57    88   1,59
2     h        40    81   1,66
3     h        46    73   1,66
4     m        67    97   1,68
5     m        68    99   1,58
6     m        65    85   1,56
7     h        60    70   1,65
8     h        56    94   1,72
9     m        66    68   1,51
10    h        54    87   1,73
11    h        52    87   1,82
12    m        65    82   1,58
13    m        55    79   1,55
14    m        67    91   1,61
15    h        45    96   1,78
16    h        44    92    1,8
17    m        38    65    1,6
18    h        34    75    1,7
19    h        39    84   1,67
20    m        44    81   1,66
21    m        44    73   1,66
22    m        43    97   1,68
23    h        48    95   1,58
24    h        50    89   1,56
25    m        44    71   1,65
26    h        57    94   1,72
27    m        59    68   1,51
28    h        44    91   1,73
29    h        36    83   1,82
..  ...       ...   ...    ...
70    m        52    79   1,66
71    h        65    87   1,83
72    h        55    96    1,8
73    m        67    96   1,58
74    m        45    65   1,56
75    m        44    94   1,65
76    h        38    90   1,72
77    h        34    81   1,51
78    m        39    87   1,65
79    h        44    93   1,82
80    h        38    77   1,58
81    m        71    71   1,55
82    m        78    67   1,61
83    m        55    80   1,57
84    h        44    70   1,56
85    h        43    94   1,72
86    m        48    64   1,51
87    h        50    87   1,73
88    h        39    83   1,82
89    m        44    86   1,58
90    m        38    75   1,55
91    m        34    71   1,61
92    h        39    85   1,78
93    h        55    96    1,8
94    m        72    65    1,6
95    h        43    90    1,7
96    m        48    93   1,73
97    h        50    79    1,7
98    h        45    88    1,6
99    m        58    81   1,66

[100 rows x 4 columns]

In [17]:
type for data

SyntaxError: invalid syntax (<ipython-input-17-cd964cf1dff2>, line 1)

In [18]:
type  data

SyntaxError: invalid syntax (<ipython-input-18-3973d1d14063>, line 1)

In [19]:
type data

SyntaxError: invalid syntax (<ipython-input-19-535469f3b21b>, line 1)

In [20]:
type(data)

pandas.core.frame.DataFrame

In [21]:
AlturadatosX = data["Estatura","Peso","Altura"]

KeyError: ('Estatura', 'Peso', 'Altura')

In [22]:
AlturadatosX = data[["Estatura","Peso","Altura"]

SyntaxError: unexpected EOF while parsing (<ipython-input-22-750f83a76a0f>, line 1)

In [23]:
AlturadatosX = [data['Estatura'],data['Peso'],data['Altura']]

In [24]:
AlturadatosX

[0     35
 1     57
 2     40
 3     46
 4     67
 5     68
 6     65
 7     60
 8     56
 9     66
 10    54
 11    52
 12    65
 13    55
 14    67
 15    45
 16    44
 17    38
 18    34
 19    39
 20    44
 21    44
 22    43
 23    48
 24    50
 25    44
 26    57
 27    59
 28    44
 29    36
       ..
 70    52
 71    65
 72    55
 73    67
 74    45
 75    44
 76    38
 77    34
 78    39
 79    44
 80    38
 81    71
 82    78
 83    55
 84    44
 85    43
 86    48
 87    50
 88    39
 89    44
 90    38
 91    34
 92    39
 93    55
 94    72
 95    43
 96    48
 97    50
 98    45
 99    58
 Name: Estatura, Length: 100, dtype: int64, 0     75
 1     88
 2     81
 3     73
 4     97
 5     99
 6     85
 7     70
 8     94
 9     68
 10    87
 11    87
 12    82
 13    79
 14    91
 15    96
 16    92
 17    65
 18    75
 19    84
 20    81
 21    73
 22    97
 23    95
 24    89
 25    71
 26    94
 27    68
 28    91
 29    83
       ..
 70    79
 71    87
 72    96
 73    96
 74    65
 75    94
 76    90
 77    81
 78    87
 79    93
 80    77
 81    71
 82    67
 83    80
 84    70
 85    94
 86    64
 87    87
 88    83
 89    86
 90    75
 91    71
 92    85
 93    96
 94    65
 95    90
 96    93
 97    79
 98    88
 99    81
 Name: Peso, Length: 100, dtype: int64, 0      1,7
 1     1,59
 2     1,66
 3     1,66
 4     1,68
 5     1,58
 6     1,56
 7     1,65
 8     1,72
 9     1,51
 10    1,73
 11    1,82
 12    1,58
 13    1,55
 14    1,61
 15    1,78
 16     1,8
 17     1,6
 18     1,7
 19    1,67
 20    1,66
 21    1,66
 22    1,68
 23    1,58
 24    1,56
 25    1,65
 26    1,72
 27    1,51
 28    1,73
 29    1,82
       ...
 70    1,66
 71    1,83
 72     1,8
 73    1,58
 74    1,56
 75    1,65
 76    1,72
 77    1,51
 78    1,65
 79    1,82
 80    1,58
 81    1,55
 82    1,61
 83    1,57
 84    1,56
 85    1,72
 86    1,51
 87    1,73
 88    1,82
 89    1,58
 90    1,55
 91    1,61
 92    1,78
 93     1,8
 94     1,6
 95     1,7
 96    1,73
 97     1,7
 98     1,6
 99    1,66
 Name: Altura, Length: 100, dtype: object]

In [25]:
data

   Sexo  Estatura  Peso Altura
0     h        35    75    1,7
1     m        57    88   1,59
2     h        40    81   1,66
3     h        46    73   1,66
4     m        67    97   1,68
5     m        68    99   1,58
6     m        65    85   1,56
7     h        60    70   1,65
8     h        56    94   1,72
9     m        66    68   1,51
10    h        54    87   1,73
11    h        52    87   1,82
12    m        65    82   1,58
13    m        55    79   1,55
14    m        67    91   1,61
15    h        45    96   1,78
16    h        44    92    1,8
17    m        38    65    1,6
18    h        34    75    1,7
19    h        39    84   1,67
20    m        44    81   1,66
21    m        44    73   1,66
22    m        43    97   1,68
23    h        48    95   1,58
24    h        50    89   1,56
25    m        44    71   1,65
26    h        57    94   1,72
27    m        59    68   1,51
28    h        44    91   1,73
29    h        36    83   1,82
..  ...       ...   ...    ...
70    m        52    79   1,66
71    h        65    87   1,83
72    h        55    96    1,8
73    m        67    96   1,58
74    m        45    65   1,56
75    m        44    94   1,65
76    h        38    90   1,72
77    h        34    81   1,51
78    m        39    87   1,65
79    h        44    93   1,82
80    h        38    77   1,58
81    m        71    71   1,55
82    m        78    67   1,61
83    m        55    80   1,57
84    h        44    70   1,56
85    h        43    94   1,72
86    m        48    64   1,51
87    h        50    87   1,73
88    h        39    83   1,82
89    m        44    86   1,58
90    m        38    75   1,55
91    m        34    71   1,61
92    h        39    85   1,78
93    h        55    96    1,8
94    m        72    65    1,6
95    h        43    90    1,7
96    m        48    93   1,73
97    h        50    79    1,7
98    h        45    88    1,6
99    m        58    81   1,66

[100 rows x 4 columns]

In [26]:
for element in data.rows
    print row['Sexo']

SyntaxError: invalid syntax (<ipython-input-26-5868dc9bfe42>, line 1)

In [27]:
for element in data.rows
    print row['Sexo']

SyntaxError: invalid syntax (<ipython-input-27-5868dc9bfe42>, line 1)

In [28]:
for element in data
    print row['Sexo']

SyntaxError: invalid syntax (<ipython-input-28-f3ac5afb35d6>, line 1)

In [29]:
for element in data.rows:
    print row['Sexo']

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(row['Sexo'])? (<ipython-input-29-683169873c6c>, line 2)

In [30]:
for element in data
    print(row['Sexo'])

SyntaxError: invalid syntax (<ipython-input-30-dc1ef8b3eb7c>, line 1)

In [31]:
for element in data:
    print(row['Sexo'])

NameError: name 'row' is not defined

In [32]:
for element in data.rows:
    print(element['Sexo'])

AttributeError: 'DataFrame' object has no attribute 'rows'

In [33]:
for element in data:
    print(element['Sexo'])

TypeError: string indices must be integers

In [34]:
for index, row in data.iterrows():
    print(row['c1'], row['c2'])

KeyError: 'c1'

In [35]:
for index, row in data.iterrows():
    print(row['Sexo'], row['Altura'])

h 1,7
m 1,59
h 1,66
h 1,66
m 1,68
m 1,58
m 1,56
h 1,65
h 1,72
m 1,51
h 1,73
h 1,82
m 1,58
m 1,55
m 1,61
h 1,78
h 1,8
m 1,6
h 1,7
h 1,67
m 1,66
m 1,66
m 1,68
h 1,58
h 1,56
m 1,65
h 1,72
m 1,51
h 1,73
h 1,82
m 1,58
m 1,55
m 1,61
h 1,78
h 1,8
m 1,6
h 1,7
h 1,78
m 1,66
m 1,66
m 1,68
h 1,81
h 1,74
m 1,65
h 1,72
h 1,79
m 1,73
m 1,82
m 1,58
h 1,55
h 1,61
m 1,78
h 1,8
m 1,6
h 1,7
h 1,73
m 1,63
m 1,7
m 1,59
h 1,66
h 1,66
m 1,6
h 1,58
m 1,78
m 1,62
m 1,6
h 1,7
h 1,73
m 1,7
h 1,86
m 1,66
h 1,83
h 1,8
m 1,58
m 1,56
m 1,65
h 1,72
h 1,51
m 1,65
h 1,82
h 1,58
m 1,55
m 1,61
m 1,57
h 1,56
h 1,72
m 1,51
h 1,73
h 1,82
m 1,58
m 1,55
m 1,61
h 1,78
h 1,8
m 1,6
h 1,7
m 1,73
h 1,7
h 1,6
m 1,66

In [36]:
sexos = []
datosComparativos = []
for index, row in data.iterrows():
    sexos.append(row['Sexo'])

In [37]:
for index, row in data.iterrows():
    datosComparativos.append(row['Estatura'],row['Peso'],row['Altura'])

TypeError: append() takes exactly one argument (3 given)

In [38]:
for index, row in data.iterrows():
    datosComparativos.append([row['Estatura'],row['Peso'],row['Altura']])

In [39]:
datosComparativos

[[35, 75, '1,7'],
 [57, 88, '1,59'],
 [40, 81, '1,66'],
 [46, 73, '1,66'],
 [67, 97, '1,68'],
 [68, 99, '1,58'],
 [65, 85, '1,56'],
 [60, 70, '1,65'],
 [56, 94, '1,72'],
 [66, 68, '1,51'],
 [54, 87, '1,73'],
 [52, 87, '1,82'],
 [65, 82, '1,58'],
 [55, 79, '1,55'],
 [67, 91, '1,61'],
 [45, 96, '1,78'],
 [44, 92, '1,8'],
 [38, 65, '1,6'],
 [34, 75, '1,7'],
 [39, 84, '1,67'],
 [44, 81, '1,66'],
 [44, 73, '1,66'],
 [43, 97, '1,68'],
 [48, 95, '1,58'],
 [50, 89, '1,56'],
 [44, 71, '1,65'],
 [57, 94, '1,72'],
 [59, 68, '1,51'],
 [44, 91, '1,73'],
 [36, 83, '1,82'],
 [39, 86, '1,58'],
 [56, 75, '1,55'],
 [55, 87, '1,61'],
 [28, 96, '1,78'],
 [38, 96, '1,8'],
 [55, 69, '1,6'],
 [45, 79, '1,7'],
 [35, 84, '1,78'],
 [46, 81, '1,66'],
 [57, 73, '1,66'],
 [55, 82, '1,68'],
 [47, 90, '1,81'],
 [44, 85, '1,74'],
 [49, 70, '1,65'],
 [66, 98, '1,72'],
 [43, 84, '1,79'],
 [67, 91, '1,73'],
 [77, 87, '1,82'],
 [74, 82, '1,58'],
 [45, 79, '1,55'],
 [49, 91, '1,61'],
 [57, 96, '1,78'],
 [62, 92, '1,8'],
 [49, 69, '1,6'],
 [34, 90, '1,7'],
 [55, 93, '1,73'],
 [28, 87, '1,63'],
 [38, 75, '1,7'],
 [55, 84, '1,59'],
 [45, 77, '1,66'],
 [35, 73, '1,66'],
 [46, 70, '1,6'],
 [57, 95, '1,58'],
 [55, 85, '1,78'],
 [47, 70, '1,62'],
 [44, 98, '1,6'],
 [49, 88, '1,7'],
 [56, 91, '1,73'],
 [66, 87, '1,7'],
 [54, 98, '1,86'],
 [52, 79, '1,66'],
 [65, 87, '1,83'],
 [55, 96, '1,8'],
 [67, 96, '1,58'],
 [45, 65, '1,56'],
 [44, 94, '1,65'],
 [38, 90, '1,72'],
 [34, 81, '1,51'],
 [39, 87, '1,65'],
 [44, 93, '1,82'],
 [38, 77, '1,58'],
 [71, 71, '1,55'],
 [78, 67, '1,61'],
 [55, 80, '1,57'],
 [44, 70, '1,56'],
 [43, 94, '1,72'],
 [48, 64, '1,51'],
 [50, 87, '1,73'],
 [39, 83, '1,82'],
 [44, 86, '1,58'],
 [38, 75, '1,55'],
 [34, 71, '1,61'],
 [39, 85, '1,78'],
 [55, 96, '1,8'],
 [72, 65, '1,6'],
 [43, 90, '1,7'],
 [48, 93, '1,73'],
 [50, 79, '1,7'],
 [45, 88, '1,6'],
 [58, 81, '1,66']]

In [40]:
type(datosComparativos)

list

In [41]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(datosComparativos,sexos)

ValueError: could not convert string to float: '1,7'

In [42]:
nuevosDatosComparativos = []
for index, row in data.iterrows():
    nuevosDatosComparativos.append(row['Estatura'],row['Peso'],row['Altura'].replace(",", "."))

TypeError: append() takes exactly one argument (3 given)

In [43]:
nuevosDatosComparativos = []
for index, row in data.iterrows():
    nuevosDatosComparativos.append([row['Estatura'],row['Peso'],row['Altura'].replace(",", ".")])

In [44]:
nuevosDatosComparativos

[[35, 75, '1.7'],
 [57, 88, '1.59'],
 [40, 81, '1.66'],
 [46, 73, '1.66'],
 [67, 97, '1.68'],
 [68, 99, '1.58'],
 [65, 85, '1.56'],
 [60, 70, '1.65'],
 [56, 94, '1.72'],
 [66, 68, '1.51'],
 [54, 87, '1.73'],
 [52, 87, '1.82'],
 [65, 82, '1.58'],
 [55, 79, '1.55'],
 [67, 91, '1.61'],
 [45, 96, '1.78'],
 [44, 92, '1.8'],
 [38, 65, '1.6'],
 [34, 75, '1.7'],
 [39, 84, '1.67'],
 [44, 81, '1.66'],
 [44, 73, '1.66'],
 [43, 97, '1.68'],
 [48, 95, '1.58'],
 [50, 89, '1.56'],
 [44, 71, '1.65'],
 [57, 94, '1.72'],
 [59, 68, '1.51'],
 [44, 91, '1.73'],
 [36, 83, '1.82'],
 [39, 86, '1.58'],
 [56, 75, '1.55'],
 [55, 87, '1.61'],
 [28, 96, '1.78'],
 [38, 96, '1.8'],
 [55, 69, '1.6'],
 [45, 79, '1.7'],
 [35, 84, '1.78'],
 [46, 81, '1.66'],
 [57, 73, '1.66'],
 [55, 82, '1.68'],
 [47, 90, '1.81'],
 [44, 85, '1.74'],
 [49, 70, '1.65'],
 [66, 98, '1.72'],
 [43, 84, '1.79'],
 [67, 91, '1.73'],
 [77, 87, '1.82'],
 [74, 82, '1.58'],
 [45, 79, '1.55'],
 [49, 91, '1.61'],
 [57, 96, '1.78'],
 [62, 92, '1.8'],
 [49, 69, '1.6'],
 [34, 90, '1.7'],
 [55, 93, '1.73'],
 [28, 87, '1.63'],
 [38, 75, '1.7'],
 [55, 84, '1.59'],
 [45, 77, '1.66'],
 [35, 73, '1.66'],
 [46, 70, '1.6'],
 [57, 95, '1.58'],
 [55, 85, '1.78'],
 [47, 70, '1.62'],
 [44, 98, '1.6'],
 [49, 88, '1.7'],
 [56, 91, '1.73'],
 [66, 87, '1.7'],
 [54, 98, '1.86'],
 [52, 79, '1.66'],
 [65, 87, '1.83'],
 [55, 96, '1.8'],
 [67, 96, '1.58'],
 [45, 65, '1.56'],
 [44, 94, '1.65'],
 [38, 90, '1.72'],
 [34, 81, '1.51'],
 [39, 87, '1.65'],
 [44, 93, '1.82'],
 [38, 77, '1.58'],
 [71, 71, '1.55'],
 [78, 67, '1.61'],
 [55, 80, '1.57'],
 [44, 70, '1.56'],
 [43, 94, '1.72'],
 [48, 64, '1.51'],
 [50, 87, '1.73'],
 [39, 83, '1.82'],
 [44, 86, '1.58'],
 [38, 75, '1.55'],
 [34, 71, '1.61'],
 [39, 85, '1.78'],
 [55, 96, '1.8'],
 [72, 65, '1.6'],
 [43, 90, '1.7'],
 [48, 93, '1.73'],
 [50, 79, '1.7'],
 [45, 88, '1.6'],
 [58, 81, '1.66']]

In [45]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(nuevosDatosComparativos,sexos)

In [46]:
prediccion = clf.predict([[19,60,1.79]])

In [47]:
prediccion

array(['h'], dtype='<U1')

In [48]:
prediccion = clf.predict([[15,60,1.53]])

In [49]:
prediccion

array(['h'], dtype='<U1')

In [50]:
prediccion = clf.predict([[15,40,1.53]])

In [51]:
prediccion

array(['h'], dtype='<U1')

In [52]:
print prediccion

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(prediccion)? (<ipython-input-52-7fa92c154c8f>, line 1)

In [53]:
print(prediccion)

['h']

In [54]:
prediccion = clf.predict([[57,88,1.59]])

In [55]:
print(prediccion)

['m']

In [56]:
prediccion = clf.predict([[56,88,1.59]])

In [57]:
print(prediccion)

['m']

In [58]:
prediccion = clf.predict([[55,88,1.59]])

In [59]:
print(prediccion)

['m']

In [60]:
prediccion = clf.predict([[17,55,1.60]])

In [61]:
print(prediccion)

['m']

In [64]:
prediccion = clf.predict([[19,65,1.78]])

In [65]:
print(prediccion)

['h']

In [66]:
data

   Sexo  Estatura  Peso Altura
0     h        35    75    1,7
1     m        57    88   1,59
2     h        40    81   1,66
3     h        46    73   1,66
4     m        67    97   1,68
5     m        68    99   1,58
6     m        65    85   1,56
7     h        60    70   1,65
8     h        56    94   1,72
9     m        66    68   1,51
10    h        54    87   1,73
11    h        52    87   1,82
12    m        65    82   1,58
13    m        55    79   1,55
14    m        67    91   1,61
15    h        45    96   1,78
16    h        44    92    1,8
17    m        38    65    1,6
18    h        34    75    1,7
19    h        39    84   1,67
20    m        44    81   1,66
21    m        44    73   1,66
22    m        43    97   1,68
23    h        48    95   1,58
24    h        50    89   1,56
25    m        44    71   1,65
26    h        57    94   1,72
27    m        59    68   1,51
28    h        44    91   1,73
29    h        36    83   1,82
..  ...       ...   ...    ...
70    m        52    79   1,66
71    h        65    87   1,83
72    h        55    96    1,8
73    m        67    96   1,58
74    m        45    65   1,56
75    m        44    94   1,65
76    h        38    90   1,72
77    h        34    81   1,51
78    m        39    87   1,65
79    h        44    93   1,82
80    h        38    77   1,58
81    m        71    71   1,55
82    m        78    67   1,61
83    m        55    80   1,57
84    h        44    70   1,56
85    h        43    94   1,72
86    m        48    64   1,51
87    h        50    87   1,73
88    h        39    83   1,82
89    m        44    86   1,58
90    m        38    75   1,55
91    m        34    71   1,61
92    h        39    85   1,78
93    h        55    96    1,8
94    m        72    65    1,6
95    h        43    90    1,7
96    m        48    93   1,73
97    h        50    79    1,7
98    h        45    88    1,6
99    m        58    81   1,66

[100 rows x 4 columns]